spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/controlsystem?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
        type: trace
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
